// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ImageExample {
	
	
	// Base type probably should be MonoTouch.Foundation.NSObject or subclass
	[MonoTouch.Foundation.Register("AppDelegate")]
	public partial class AppDelegate {
		
		private MonoTouch.UIKit.UIWindow __mt_window;
		
		private MonoTouch.UIKit.UIImageView __mt_bundleImage;
		
		private MonoTouch.UIKit.UIImageView __mt_folderImage;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("window")]
		private MonoTouch.UIKit.UIWindow window {
			get {
				this.__mt_window = ((MonoTouch.UIKit.UIWindow)(this.GetNativeField("window")));
				return this.__mt_window;
			}
			set {
				this.__mt_window = value;
				this.SetNativeField("window", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("bundleImage")]
		private MonoTouch.UIKit.UIImageView bundleImage {
			get {
				this.__mt_bundleImage = ((MonoTouch.UIKit.UIImageView)(this.GetNativeField("bundleImage")));
				return this.__mt_bundleImage;
			}
			set {
				this.__mt_bundleImage = value;
				this.SetNativeField("bundleImage", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("folderImage")]
		private MonoTouch.UIKit.UIImageView folderImage {
			get {
				this.__mt_folderImage = ((MonoTouch.UIKit.UIImageView)(this.GetNativeField("folderImage")));
				return this.__mt_folderImage;
			}
			set {
				this.__mt_folderImage = value;
				this.SetNativeField("folderImage", value);
			}
		}
	}
}
